plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ingeniousidea.space'
    compileSdk 34

    defaultConfig {
        applicationId "com.ingeniousidea.space"
        minSdk 23
        targetSdk 34
        versionCode 44
        versionName "5.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
